version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: crawler_pg
    environment:
      POSTGRES_DB: crawler
      POSTGRES_USER: crawler
      POSTGRES_PASSWORD: crawler
    ports:
      - "5433:5432" # change host port to 5433
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crawler -d crawler"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: crawler_redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  # Optional: local S3 for storing page HTML blobs (enable later)
  localstack:
    image: localstack/localstack:3
    container_name: crawler_localstack
    environment:
      SERVICES: s3
    ports:
      - "4566:4566"

volumes:
  pgdata:
  redisdata:
